### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by Pauan** [regiontog/gensym#1]
Hi! Thanks for your very useful crate. The dependencies are very outdated, which is causing duplication. It would be great if they could be updated:

```toml
uuid = { version = "1.3.0", features = ["v4"] }
syn = { version = "2.0.8", features = ["full"] }
proc-macro2 = "1.0.53"
quote = "1.0.26"
```

This is a breaking change, but on the plus side all of the dependencies are now `1.x` which means that gensym can also be `1.x`
